'use client';

import { useState } from 'react';
import Link from 'next/link';
import { Copy, Download, FileText, Languages, Loader2, RotateCcw, Sparkles, X } from 'lucide-react';
import { FileDropzone } from '@/components/pdf/file-dropzone';
import { ToolLayout } from '@/components/pdf/tool-layout';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import { extractTextFromPDF } from '@/lib/pdf/convert';
import { pdfTools } from '@/lib/config/tools';

const languages = ['English', 'Spanish', 'French', 'German', 'Italian', 'Portuguese', 'Dutch', 'Russian', 'Arabic', 'Urdu', 'Hindi', 'Bengali', 'Chinese', 'Japanese', 'Korean', 'Turkish', 'Polish', 'Indonesian'];

type Props = { mode: 'summarize' | 'translate' };
export function PdfIntelligenceTool({ mode }: Props) {
  const tool = pdfTools.find((item) => item.id === `${mode}-pdf`)!;
  const [file, setFile] = useState<File | null>(null); const [pages, setPages] = useState<string[]>([]); const [result, setResult] = useState(''); const [busy, setBusy] = useState(false); const [status, setStatus] = useState(''); const [error, setError] = useState('');
  const [summaryType, setSummaryType] = useState('Quick Summary'); const [length, setLength] = useState('Medium'); const [target, setTarget] = useState('English'); const [source, setSource] = useState('auto');
  async function select(files: File[]) { const picked = files[0]; if (!picked) return; if (picked.size > 25 * 1024 * 1024) { setError('Please choose a PDF smaller than 25 MB.'); return; } setFile(picked); setResult(''); setError(''); setStatus('Extracting text…'); try { const extracted = await extractTextFromPDF(picked); setPages(extracted); setStatus(`Ready · ${extracted.length} page${extracted.length === 1 ? '' : 's'}`); } catch { setError('This PDF could not be read. It may be corrupted or password-protected.'); setStatus(''); } }
  async function process() { if (!pages.length) return; setBusy(true); setError(''); setStatus(mode === 'summarize' ? 'Creating summary…' : 'Translating document…'); try { const response = await fetch(`/api/ai/${mode}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(mode === 'summarize' ? { pages, type: summaryType, length } : { pages, target, source }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setResult(data.result); setStatus('Complete'); } catch (err) { setError(err instanceof Error ? err.message : 'The AI service is unavailable right now.'); setStatus(''); } finally { setBusy(false); } }
  function reset() { setFile(null); setPages([]); setResult(''); setError(''); setStatus(''); }
  function download(ext: string) { const blob = new Blob([result], { type: 'text/plain;charset=utf-8' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `${file?.name.replace(/\.pdf$/i, '') || mode}-${mode}.${ext}`; link.click(); URL.revokeObjectURL(url); }
  return <ToolLayout title={tool.name} description={tool.description} icon={tool.icon} color={tool.color}>
    <div className="mx-auto flex max-w-3xl flex-col gap-6">
      {!result && !file && <FileDropzone onFilesSelected={select} multiple={false} />}
      {file && !result && <Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle className="flex items-center gap-2"><FileText className="size-5 text-primary" />{file.name}</CardTitle><Button variant="ghost" size="icon" onClick={reset} aria-label="Remove PDF"><X /></Button></CardHeader><CardContent className="flex flex-col gap-6"><p className="text-sm text-muted-foreground">{(file.size / 1024 / 1024).toFixed(2)} MB · {pages.length} pages</p>{mode === 'summarize' ? <div className="grid gap-4 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor="summary-type">Summary type</Label><select id="summary-type" value={summaryType} onChange={(e) => setSummaryType(e.target.value)} className="h-10 rounded-md border bg-background px-3">{['Quick Summary', 'Detailed Summary', 'Key Points', 'Executive Summary', 'Study Notes'].map((v) => <option key={v}>{v}</option>)}</select></div><div className="grid gap-2"><Label htmlFor="summary-length">Length</Label><select id="summary-length" value={length} onChange={(e) => setLength(e.target.value)} className="h-10 rounded-md border bg-background px-3">{['Short', 'Medium', 'Detailed'].map((v) => <option key={v}>{v}</option>)}</select></div></div> : <div className="grid gap-4 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor="source">Translate from</Label><select id="source" value={source} onChange={(e) => setSource(e.target.value)} className="h-10 rounded-md border bg-background px-3"><option value="auto">Auto Detect</option>{languages.map((v) => <option key={v}>{v}</option>)}</select></div><div className="grid gap-2"><Label htmlFor="target">Translate to</Label><select id="target" value={target} onChange={(e) => setTarget(e.target.value)} className="h-10 rounded-md border bg-background px-3">{languages.map((v) => <option key={v}>{v}</option>)}</select></div></div>}<p className="text-xs leading-5 text-muted-foreground">Your PDF stays in the browser. Only extracted text is sent to the AI provider for processing. Do not include sensitive information you are not comfortable sending.</p><Button onClick={process} disabled={busy || !pages.length}>{busy ? <Loader2 className="animate-spin" data-icon="inline-start" /> : mode === 'summarize' ? <Sparkles data-icon="inline-start" /> : <Languages data-icon="inline-start" />}{busy ? 'Processing…' : mode === 'summarize' ? 'Summarize PDF' : 'Translate PDF'}</Button></CardContent></Card>}
      {status && <p role="status" className="text-center text-sm text-muted-foreground">{status}</p>}{error && <div role="alert" className="rounded-lg border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">{error} {error.toLowerCase().includes('text') && <Link className="underline" href="/tools/ocr">Try OCR Scanner</Link>}</div>}
      {result && <Card><CardHeader><CardTitle>{mode === 'summarize' ? 'Summary' : 'Translation Complete'}</CardTitle></CardHeader><CardContent className="flex flex-col gap-4"><article className="min-h-[360px] whitespace-pre-wrap rounded-lg border bg-muted/20 p-5 text-sm leading-7">{result}</article><div className="flex flex-wrap gap-2"><Button onClick={() => navigator.clipboard.writeText(result)}><Copy data-icon="inline-start" />Copy</Button><Button variant="outline" onClick={() => download('txt')}><Download data-icon="inline-start" />Download TXT</Button><Button variant="outline" onClick={() => download('md')}>Download Markdown</Button><Button variant="ghost" onClick={reset}><RotateCcw data-icon="inline-start" />Start again</Button></div></CardContent></Card>}
    </div>
  </ToolLayout>;
}
