import Link from 'next/link';

export type ToolSeoContent = {
  title: string;
  description: string;
  metaTitle: string;
  metaDescription: string;
  intro: string;
  howTo: string[];
  details: string;
  useCases: string[];
  privacy: string;
  faqs: { question: string; answer: string }[];
  related: { href: string; label: string }[];
};

const content: Record<string, ToolSeoContent> = {
  'Merge PDF': {
    title: 'Merge PDF files online', description: 'Combine multiple PDF files into one document', metaTitle: 'Merge PDF Files Online Free | SelfPDF', metaDescription: 'Combine PDF files in the order you choose with SelfPDF. Merge documents in your browser and download one organized PDF.', intro: 'Merge PDF files when reports, scanned pages, or project documents belong in one clean file. SelfPDF lets you upload several PDFs, arrange their order, and download the combined document.', howTo: ['Choose or drop the PDF files you want to combine.', 'Drag files into the order they should appear.', 'Select Merge and save the finished PDF with your preferred filename.'], details: 'The merge tool joins complete PDF documents without asking you to re-create their text or layout. It is useful for assembling invoices, applications, research material, and client deliverables.', useCases: ['Combine scanned pages into one document', 'Assemble a report with separate appendices', 'Put several invoices or receipts into one file'], privacy: 'Files are processed in your browser by the existing SelfPDF tool. The page does not require an account or a file upload service to combine your documents.', faqs: [{question:'Can I change the PDF order?',answer:'Yes. Drag the files into the order you want before merging.'},{question:'How many PDFs can I merge?',answer:'The tool accepts multiple PDF files. Your browser and available memory determine practical limits.'},{question:'Will the original files change?',answer:'No. Merging creates a new PDF and leaves your original files unchanged.'},{question:'Can I merge scanned PDFs?',answer:'Yes. Scanned PDFs can be combined like other PDF files.'},{question:'Is the merged PDF downloaded immediately?',answer:'After processing, choose a filename and download the new document.'}], related: [{href:'/tools/split',label:'split a PDF into separate files'}, {href:'/tools/compress',label:'compress the finished PDF'}]
  },
  'Compress PDF': {
    title: 'Compress PDF files online', description: 'Reduce PDF file size while maintaining quality', metaTitle: 'Compress PDF Online Free | Reduce PDF Size | SelfPDF', metaDescription: 'Reduce PDF file size for email, uploads, and sharing with SelfPDF. Compress one PDF in your browser and download the smaller file.', intro: 'Large PDFs are difficult to email and upload. SelfPDF compresses a PDF into a smaller copy so it is easier to share while preserving the document structure supported by the tool.', howTo: ['Drop one PDF into the compressor.', 'Select Compress PDF and wait while the browser processes it.', 'Compare the original and compressed sizes, then download the result.'], details: 'PDF compression removes unnecessary file weight from a document. It is especially helpful for scanned paperwork, exported presentations, and files that exceed an attachment or portal limit.', useCases: ['Prepare a PDF for email attachment', 'Reduce a document before uploading to a form', 'Make a portfolio or presentation easier to share'], privacy: 'Compression runs through the current browser-based tool. Your PDF is handled locally by the page rather than sent to an advertising or analytics service.', faqs: [{question:'Does compression always make a PDF smaller?',answer:'The result depends on the document. PDFs that are already optimized may change little.'},{question:'Will compression remove my text?',answer:'The tool is designed to preserve the PDF document rather than convert it into a new text file.'},{question:'Can I compress more than one PDF at once?',answer:'This tool processes one PDF at a time.'},{question:'What is a good PDF size for email?',answer:'Many email services set their own attachment limits, so compress until the file fits your recipient’s service.'},{question:'Can I compress a PDF on my phone?',answer:'Yes, if your mobile browser supports the file picker and has enough memory for the document.'}], related: [{href:'/tools/merge',label:'merge PDFs before compressing'}, {href:'/tools/pdf-to-images',label:'convert a PDF to images'}]
  },
};

const fallback = (title: string, description: string): ToolSeoContent => ({ title, description, metaTitle: `${title} | SelfPDF`, metaDescription: `${description}. Use SelfPDF in your browser with a simple, private PDF workflow.`, intro: `${title} is designed for a focused PDF task without unnecessary steps. Use the tool above to work with your document, then read the guide for practical tips.`, howTo: ['Select a file using the upload area above.', `Choose ${title} to process the document.`, 'Download the result when processing is complete.'], details: `Use ${title.toLowerCase()} when you need a straightforward way to prepare, edit, convert, or organize a PDF. The tool keeps the workflow focused so you can finish the task quickly.`, useCases: ['Prepare documents for sharing', 'Organize files for work or school', 'Create a cleaner copy for archiving'], privacy: 'This explanation reflects the browser-based workflow used by SelfPDF. Do not upload documents you are not authorized to process.', faqs: [{question:`What does ${title} do?`,answer:description + '.'},{question:'Do I need an account?',answer:'No account is required for the tool workflow.'},{question:'What file should I select?',answer:'Use the file type accepted by the upload area above.'},{question:'Can I use it on mobile?',answer:'Yes, provided your browser can select and download files.'},{question:'Where is my result saved?',answer:'The processed file is downloaded through your browser.'}], related: [{href:'/tools',label:'browse all PDF tools'}]});

export function getToolSeoContent(title: string, description: string) { return content[title] ?? fallback(title, description); }

export function ToolSeoContent({ data }: { data: ToolSeoContent }) {
  return <section className="mx-auto max-w-4xl space-y-10" aria-label={`${data.title} guide`}>
    <div className="space-y-3"><p className="text-lg leading-7 text-muted-foreground">{data.intro}</p></div>
    <div className="grid gap-8 md:grid-cols-2"><div><h2 className="mb-4 text-2xl font-semibold">How to use {data.title}</h2><ol className="space-y-3 text-muted-foreground">{data.howTo.map((step, i) => <li key={step} className="flex gap-3"><span className="font-semibold text-foreground">{i + 1}.</span><span>{step}</span></li>)}</ol></div><div><h2 className="mb-4 text-2xl font-semibold">About this PDF tool</h2><p className="leading-7 text-muted-foreground">{data.details}</p></div></div>
    <div><h2 className="mb-4 text-2xl font-semibold">Common uses</h2><ul className="grid gap-3 text-muted-foreground sm:grid-cols-3">{data.useCases.map((item) => <li key={item} className="rounded-xl border bg-muted/20 p-4">{item}</li>)}</ul></div>
    <div className="rounded-2xl border bg-muted/20 p-6"><h2 className="mb-3 text-2xl font-semibold">Privacy and local processing</h2><p className="leading-7 text-muted-foreground">{data.privacy}</p></div>
    <div><h2 className="mb-5 text-2xl font-semibold">Frequently Asked Questions</h2><div className="space-y-6">{data.faqs.map((faq) => <div key={faq.question}><h3 className="font-semibold">{faq.question}</h3><p className="mt-2 leading-7 text-muted-foreground">{faq.answer}</p></div>)}</div></div>
    <nav aria-label="Related PDF tools" className="border-t pt-6"><h2 className="mb-3 text-lg font-semibold">Related tools</h2><div className="flex flex-wrap gap-x-5 gap-y-2">{data.related.map((link) => <Link key={link.href} href={link.href} className="text-primary underline-offset-4 hover:underline">{link.label}</Link>)}</div></nav>
  </section>;
}

export function getToolMetadata(title: string, description: string, path: string) { const data = getToolSeoContent(title, description); return { title: data.metaTitle, description: data.metaDescription, alternates: { canonical: `https://selfpdf.com${path}` }, openGraph: { title: data.metaTitle, description: data.metaDescription, url: `https://selfpdf.com${path}`, type: 'website' as const, siteName: 'SelfPDF' }, twitter: { card: 'summary' as const, title: data.metaTitle, description: data.metaDescription } }; }
