import Link from 'next/link';

export type ToolSeoContent = {
  title: string;
  description: string;
  metaTitle: string;
  metaDescription: string;
  intro: string;
  howTo: string[];
  details: string;
  useCases: string[];
  privacy: string;
  faqs: { question: string; answer: string }[];
  related: { href: string; label: string }[];
};

type ToolProfile = Pick<ToolSeoContent, 'intro' | 'howTo' | 'details' | 'useCases' | 'faqs' | 'related'> & { keywords: string[] };

const profiles: Record<string, ToolProfile> = {
  'Merge PDF': { keywords: ['merge PDF online', 'combine PDF files', 'join PDFs'], intro: 'Combine PDF files into one ordered document for sharing, printing, or archiving. SelfPDF keeps this workflow focused: choose your files, arrange the pages, and download one merged PDF.', howTo: ['Select the PDF files you want to combine.', 'Arrange the files in the order they should appear.', 'Start the merge, choose a filename, and download the new PDF.'], details: 'Merging is useful when a report, application, invoice set, or scanned packet is spread across several PDFs. The original files stay unchanged while SelfPDF creates a single combined document.', useCases: ['Combine reports and appendices', 'Join scanned pages or receipts', 'Prepare one attachment for email'], faqs: [{ question: 'Can I reorder PDFs before merging?', answer: 'Yes. Arrange the uploaded files in your preferred reading order before starting.' }, { question: 'Are my original files changed?', answer: 'No. The merge creates a separate PDF and does not modify your source files.' }, { question: 'Can I merge scanned PDFs?', answer: 'Yes. Scanned PDF files can be combined with other PDFs.' }], related: [{ href: '/tools/split', label: 'split PDF pages' }, { href: '/tools/compress', label: 'compress a merged PDF' }] },
  'Compress PDF': { keywords: ['compress PDF online', 'reduce PDF size', 'PDF compressor'], intro: 'Reduce PDF file size for email attachments, uploads, and faster sharing. SelfPDF creates a smaller copy in your browser without requiring an account.', howTo: ['Choose the PDF you want to optimize.', 'Start compression and wait for the browser to finish processing.', 'Review the result and download the smaller PDF.'], details: 'Compression is helpful for scanned documents, portfolios, presentations, and files that exceed a website or email attachment limit. The practical size reduction depends on how the original PDF was created.', useCases: ['Fit a PDF within an upload limit', 'Send a document by email', 'Share a smaller portfolio or presentation'], faqs: [{ question: 'Will every PDF become smaller?', answer: 'Not always. PDFs that are already optimized may show little change.' }, { question: 'Does compression delete my original?', answer: 'No. The compressed PDF is downloaded as a new copy.' }, { question: 'Can I compress multiple PDFs at once?', answer: 'The current workflow processes one PDF at a time.' }], related: [{ href: '/tools/merge', label: 'merge PDFs first' }, { href: '/tools/pdf-to-images', label: 'convert PDF pages to images' }] },
  'Split PDF': { keywords: ['split PDF online', 'extract PDF pages', 'separate PDF pages'], intro: 'Split a PDF into selected page ranges or separate page files. It is a practical way to extract only the pages needed from a long document.', howTo: ['Select the PDF you want to divide.', 'Choose the page range or extraction option.', 'Process the selection and download the resulting PDF files.'], details: 'Use PDF splitting to send one chapter, remove unrelated pages from a submission, or divide a large scan into smaller documents. Check the selected page range before downloading.', useCases: ['Extract a chapter from a report', 'Separate pages for different recipients', 'Remove unrelated pages before sharing'], faqs: [{ question: 'Can I extract just one page?', answer: 'Yes. Select a single-page range when configuring the split.' }, { question: 'Does splitting change the original PDF?', answer: 'No. It creates extracted copies and leaves the original unchanged.' }, { question: 'Why is my page range empty?', answer: 'Make sure the PDF loaded successfully and that the start and end pages are valid.' }], related: [{ href: '/tools/merge', label: 'merge extracted PDFs' }, { href: '/tools/page-numbers', label: 'add page numbers' }] },
  'PDF to Images': { keywords: ['PDF to JPG', 'PDF to PNG', 'convert PDF to images'], intro: 'Convert PDF pages into image files for presentations, previews, websites, and visual sharing. Choose the output quality supported by the tool and download the rendered pages.', howTo: ['Upload the PDF document.', 'Choose the image format and rendering options.', 'Convert the pages and download the generated images.'], details: 'PDF-to-image conversion renders each page as a visual file. It is useful when the recipient needs PNG or JPG images instead of a PDF document.', useCases: ['Create page previews', 'Share a PDF page as an image', 'Add document pages to a presentation'], faqs: [{ question: 'Which image formats are supported?', answer: 'The tool interface shows the available PNG or JPG output options.' }, { question: 'Is each PDF page converted?', answer: 'The conversion renders the pages selected by the tool.' }, { question: 'Will text remain selectable?', answer: 'No. An image is a visual rendering, so its text is not selectable like PDF text.' }], related: [{ href: '/tools/images-to-pdf', label: 'convert images back to PDF' }, { href: '/tools/compress', label: 'compress the source PDF' }] },
  'Images to PDF': { keywords: ['images to PDF', 'JPG to PDF', 'PNG to PDF'], intro: 'Turn image files into one shareable PDF document. Arrange your images in the intended order before creating the final file.', howTo: ['Select the image files you want to include.', 'Arrange the images in the desired page order.', 'Create the PDF and download the finished document.'], details: 'Images-to-PDF conversion helps with scanned paperwork, receipts, photos, and photographed notes. A single PDF is easier to print, submit, and archive than a folder of images.', useCases: ['Combine receipt photos', 'Create a scan packet', 'Turn photographed notes into a PDF'], faqs: [{ question: 'Can I reorder the images?', answer: 'Yes. Set the image order before generating the PDF.' }, { question: 'Are the images uploaded to a server?', answer: 'The current browser workflow processes the files locally in the page.' }, { question: 'Can I add more than one image?', answer: 'Yes. Select multiple supported image files for a multi-page PDF.' }], related: [{ href: '/tools/pdf-to-images', label: 'export PDF pages as images' }, { href: '/tools/scan', label: 'scan images into a PDF' }] },
  'PDF to Word': { keywords: ['PDF to Word', 'convert PDF to DOCX', 'PDF converter'], intro: 'Convert a PDF into an editable Word document when you need to revise text or continue formatting in a word processor.', howTo: ['Select a PDF file.', 'Start the PDF-to-Word conversion.', 'Download the generated Word document and review its formatting.'], details: 'Conversion results depend on the source PDF. Text-based PDFs usually convert more cleanly than scans, complex layouts, or documents with unusual fonts.', useCases: ['Edit text from a PDF', 'Reuse content in a report', 'Move a document into a Word workflow'], faqs: [{ question: 'Will the layout be identical?', answer: 'Not always. Complex columns, graphics, and fonts may need review after conversion.' }, { question: 'Can scanned PDFs be converted?', answer: 'Scanned pages may require OCR before their text can be edited reliably.' }, { question: 'Should I review the DOCX?', answer: 'Yes. Check headings, tables, spacing, and page breaks before sharing.' }], related: [{ href: '/tools/ocr', label: 'extract text with OCR' }, { href: '/tools/word-to-pdf', label: 'convert Word back to PDF' }] },
  'Word to PDF': { keywords: ['Word to PDF', 'DOCX to PDF', 'convert Word document'], intro: 'Convert a Word document into a PDF that is easier to share and preserves a consistent page-based format.', howTo: ['Select a supported Word document.', 'Start the conversion in your browser.', 'Download and check the resulting PDF before sending it.'], details: 'PDF is a useful final format for applications, invoices, resumes, and reports because recipients can view the page layout without editing the source document.', useCases: ['Export a report for submission', 'Share a resume consistently', 'Create a printable document'], faqs: [{ question: 'Does conversion edit my Word file?', answer: 'No. It creates a PDF copy and leaves the original document unchanged.' }, { question: 'Should I check the PDF?', answer: 'Yes. Review page breaks, fonts, images, and tables after conversion.' }, { question: 'Can I convert on mobile?', answer: 'Yes, when your mobile browser supports selecting and downloading the document.' }], related: [{ href: '/tools/pdf-to-word', label: 'convert PDF to Word' }, { href: '/tools/compress', label: 'reduce PDF size' }] },
  'Rotate PDF': { keywords: ['rotate PDF', 'rotate PDF pages online', 'fix PDF orientation'], intro: 'Correct sideways or upside-down PDF pages before printing, presenting, or sharing the document.', howTo: ['Choose the PDF with incorrectly oriented pages.', 'Select the rotation direction for the pages.', 'Apply the change and download the corrected PDF.'], details: 'Rotating pages changes their viewing orientation without requiring you to recreate the document. Check every page preview when a file contains mixed orientations.', useCases: ['Fix scanned pages', 'Prepare landscape forms', 'Correct a photographed document'], faqs: [{ question: 'Can I rotate individual pages?', answer: 'Use the page controls provided by the tool to apply the needed orientation.' }, { question: 'Does rotation reduce quality?', answer: 'Rotation changes page orientation; it does not intentionally compress the PDF.' }, { question: 'Can I undo rotation?', answer: 'Keep the original file so you can create another copy with the opposite rotation.' }], related: [{ href: '/tools/crop', label: 'crop PDF pages' }, { href: '/tools/merge', label: 'merge corrected PDFs' }] },
  'Unlock PDF': { keywords: ['unlock PDF', 'remove PDF password', 'decrypt PDF'], intro: 'Create an accessible copy of a PDF you are authorized to use when password protection prevents normal editing or processing.', howTo: ['Select the protected PDF.', 'Enter the password when the tool requests it.', 'Process the file and download the unlocked copy.'], details: 'Only remove protection from documents you own or have permission to process. A user password may be required, and some encryption types may not be supported by browser tools.', useCases: ['Prepare an owned PDF for editing', 'Process a protected document', 'Create a usable archive copy'], faqs: [{ question: 'Do I need the password?', answer: 'Usually, yes. Do not try to bypass protection on documents you are not authorized to access.' }, { question: 'Can every encrypted PDF be unlocked?', answer: 'Support depends on the PDF encryption and the password provided.' }, { question: 'Is the original changed?', answer: 'No. The unlocked result is a separate downloaded copy.' }], related: [{ href: '/tools/protect', label: 'protect a PDF' }, { href: '/tools/sign', label: 'sign a PDF' }] },
  'Protect PDF': { keywords: ['password protect PDF', 'encrypt PDF', 'secure PDF online'], intro: 'Add password protection to a PDF before sharing it with a recipient. Use a strong password and share it through a separate trusted channel.', howTo: ['Select the PDF you want to protect.', 'Enter and confirm a strong password.', 'Create the protected copy and download it securely.'], details: 'Password protection can reduce casual access to a document, but it does not replace careful sharing practices. Keep a secure record of the password because recovery may not be possible.', useCases: ['Protect a private report', 'Secure an invoice or form', 'Add a password before email sharing'], faqs: [{ question: 'Can SelfPDF recover my password?', answer: 'No. Keep your password safe because a forgotten password may not be recoverable.' }, { question: 'Does protection change the original?', answer: 'No. The tool creates a protected copy.' }, { question: 'Is password protection a complete security system?', answer: 'It is one safeguard. Also use secure sharing and access controls appropriate for the document.' }], related: [{ href: '/tools/unlock', label: 'unlock an authorized PDF' }, { href: '/tools/sign', label: 'sign a PDF' }] },
  'Watermark': { keywords: ['watermark PDF', 'add watermark to PDF', 'PDF watermark tool'], intro: 'Add a visible text watermark to PDF pages for draft labels, ownership notices, confidentiality reminders, or document status.', howTo: ['Select the PDF to mark.', 'Enter the watermark text and choose its placement.', 'Apply the watermark and download the new PDF.'], details: 'A watermark communicates context without changing the main document content. Use readable wording and check that it does not obscure signatures, tables, or important text.', useCases: ['Label a document as a draft', 'Add a confidentiality notice', 'Mark a PDF with organization text'], faqs: [{ question: 'Can I change the watermark text?', answer: 'Yes. Enter the wording you want before applying it.' }, { question: 'Does a watermark protect copyright by itself?', answer: 'No. It is a visual notice, not a replacement for legal or access controls.' }, { question: 'Will the watermark cover content?', answer: 'Review its placement and wording so important page content remains readable.' }], related: [{ href: '/tools/page-numbers', label: 'add PDF page numbers' }, { href: '/tools/protect', label: 'password protect the PDF' }] },
  'Page Numbers': { keywords: ['add page numbers to PDF', 'number PDF pages', 'PDF page numbering'], intro: 'Add clear page numbers to PDF pages so readers can navigate reports, proposals, manuals, and long documents.', howTo: ['Select the PDF document.', 'Choose the page-number placement and format.', 'Apply the numbering and download the finished PDF.'], details: 'Page numbers are especially useful when a document will be printed or discussed in meetings. Check the first and last pages after processing.', useCases: ['Number a business report', 'Prepare a printable manual', 'Organize a legal or school submission'], faqs: [{ question: 'Can I choose where numbers appear?', answer: 'Use the placement controls available in the page-number tool.' }, { question: 'Are existing page numbers removed?', answer: 'The tool adds numbering; review the result if the source already contains numbers.' }, { question: 'Does numbering change the PDF text?', answer: 'It adds visible page labels to the generated copy.' }], related: [{ href: '/tools/watermark', label: 'add a PDF watermark' }, { href: '/tools/rotate', label: 'rotate PDF pages' }] },
  'Sign PDF': { keywords: ['sign PDF online', 'electronic signature PDF', 'draw signature on PDF'], intro: 'Place a signature on a PDF for routine approvals, forms, and personal workflows. Review the document and use a legally appropriate signing method when required.', howTo: ['Select the PDF and open the signing workspace.', 'Create or place your signature in the document.', 'Position it correctly and download the signed copy.'], details: 'This tool places a signature mark on the PDF. It may not provide identity verification, certificates, or the legal assurances required for regulated electronic signatures.', useCases: ['Sign routine forms', 'Approve an internal document', 'Add a handwritten signature image'], faqs: [{ question: 'Is this a legally certified signature?', answer: 'Not necessarily. Requirements vary by country, document type, and organization; use a certified e-signature service when required.' }, { question: 'Can I move the signature?', answer: 'Position the signature in the signing workspace before downloading.' }, { question: 'Is the original PDF modified?', answer: 'No. The signed file is generated as a separate copy.' }], related: [{ href: '/tools/protect', label: 'protect the signed PDF' }, { href: '/tools/watermark', label: 'watermark a PDF' }] },
  'OCR Scanner': { keywords: ['OCR PDF online', 'extract text from scanned PDF', 'PDF text recognition'], intro: 'Use OCR to extract searchable text from scanned PDF pages. OCR works best with clear, high-contrast scans and may need proofreading.', howTo: ['Select a scanned PDF.', 'Start OCR processing and wait for recognition to finish.', 'Download or review the extracted text result.'], details: 'Optical character recognition turns page images into machine-readable text. Tables, handwriting, multiple columns, and low-quality scans can reduce accuracy.', useCases: ['Search a scanned archive', 'Copy text from a paper scan', 'Make a receipt or form easier to reference'], faqs: [{ question: 'Can OCR read handwriting?', answer: 'Handwriting recognition is not guaranteed and usually needs careful review.' }, { question: 'Is OCR always accurate?', answer: 'No. Proofread names, numbers, tables, and formatting before relying on the result.' }, { question: 'What scans work best?', answer: 'Clear, upright, high-resolution pages with strong contrast generally produce better results.' }], related: [{ href: '/tools/pdf-to-word', label: 'convert PDF text to Word' }, { href: '/tools/compress', label: 'compress scanned PDF files' }] },
  'PDF to PowerPoint': { keywords: ['PDF to PowerPoint', 'convert PDF to PPTX', 'PDF presentation converter'], intro: 'Convert PDF pages into a PowerPoint presentation when you need to present, reorganize, or reuse document pages in slides.', howTo: ['Select the PDF file.', 'Start the PDF-to-PowerPoint conversion.', 'Download the presentation and review each slide for layout accuracy.'], details: 'PDF pages and slide layouts work differently, so complex designs may require editing after conversion. Treat the result as an editable starting point and verify charts and text.', useCases: ['Turn a report into presentation slides', 'Reuse PDF pages in a meeting deck', 'Prepare visual material for editing'], faqs: [{ question: 'Will each page become a slide?', answer: 'The conversion is designed to turn PDF pages into presentation content; review the generated deck.' }, { question: 'Can charts be edited?', answer: 'Some content may be positioned as visual elements rather than native PowerPoint charts.' }, { question: 'Should I review the presentation?', answer: 'Yes. Check fonts, spacing, images, and slide breaks before presenting.' }], related: [{ href: '/tools/powerpoint-to-pdf', label: 'export PowerPoint to PDF' }, { href: '/tools/pdf-to-images', label: 'render pages as images' }] },
  'PowerPoint to PDF': { keywords: ['PowerPoint to PDF', 'PPTX to PDF', 'convert presentation to PDF'], intro: 'Convert a PowerPoint presentation into a PDF for consistent sharing, printing, and submission across devices.', howTo: ['Select the PowerPoint file.', 'Start the presentation-to-PDF conversion.', 'Download the PDF and review slide layout and fonts.'], details: 'PDF preserves a page-based presentation view, but animations, speaker notes, and interactive elements may not carry over. Check the exported pages before distribution.', useCases: ['Share a deck as a fixed document', 'Print presentation slides', 'Submit slides to a portal'], faqs: [{ question: 'Are animations included?', answer: 'PDF is a static format, so presentation animations and transitions are not preserved.' }, { question: 'Will speaker notes export?', answer: 'Speaker notes are not part of the normal slide-page output.' }, { question: 'Should I check the PDF?', answer: 'Yes. Verify images, fonts, charts, and slide boundaries after conversion.' }], related: [{ href: '/tools/pdf-to-powerpoint', label: 'convert PDF to PowerPoint' }, { href: '/tools/compress', label: 'compress the exported PDF' }] },
  'PDF to Excel': { keywords: ['PDF to Excel', 'convert PDF to XLSX', 'extract PDF tables'], intro: 'Convert PDF table content into an Excel workbook for analysis, sorting, and further editing.', howTo: ['Select the PDF containing table data.', 'Start the PDF-to-Excel conversion.', 'Download the workbook and verify columns, numbers, and rows.'], details: 'Table extraction works best when the source uses clear text-based rows and columns. Scans, merged cells, and complex layouts may need manual cleanup or OCR first.', useCases: ['Reuse a financial table', 'Analyze tabular report data', 'Move a schedule into a spreadsheet'], faqs: [{ question: 'Can it extract every PDF table perfectly?', answer: 'No. Results depend on table structure, scan quality, and the source PDF layout.' }, { question: 'Should I verify numbers?', answer: 'Always verify totals, decimal points, dates, and column alignment before analysis.' }, { question: 'Can scanned tables be converted?', answer: 'Scanned tables may require OCR and manual correction.' }], related: [{ href: '/tools/excel-to-pdf', label: 'convert Excel to PDF' }, { href: '/tools/ocr', label: 'read scanned PDF text' }] },
  'Excel to PDF': { keywords: ['Excel to PDF', 'XLSX to PDF', 'convert spreadsheet to PDF'], intro: 'Convert an Excel workbook into a PDF for sharing, printing, and consistent review without requiring the recipient to edit spreadsheet cells.', howTo: ['Select the Excel workbook.', 'Start the spreadsheet-to-PDF conversion.', 'Download the PDF and check sheet layout, scaling, and page breaks.'], details: 'Spreadsheets can span many columns and pages. Review the generated PDF carefully, especially print areas, hidden columns, formulas, and wide tables.', useCases: ['Share a spreadsheet report', 'Print a worksheet', 'Submit a table as a fixed document'], faqs: [{ question: 'Are formulas still editable?', answer: 'No. PDF is a fixed document format, so review the displayed values before exporting.' }, { question: 'Will every worksheet be included?', answer: 'Check the generated document and the tool options for the workbook behavior.' }, { question: 'Why does the sheet span several pages?', answer: 'Wide or long spreadsheets naturally paginate; adjust the source layout if needed.' }], related: [{ href: '/tools/pdf-to-excel', label: 'convert PDF tables to Excel' }, { href: '/tools/compress', label: 'reduce PDF size' }] },
  'Crop PDF': { keywords: ['crop PDF online', 'trim PDF margins', 'change PDF page size'], intro: 'Crop PDF page margins to remove unwanted borders, improve framing, or focus attention on the useful content area.', howTo: ['Select the PDF you want to crop.', 'Set the crop area or page margins.', 'Apply the crop and download the revised PDF.'], details: 'Cropping changes the visible page area. It does not automatically erase hidden content outside the crop boundary, so avoid using it as a confidential-redaction method.', useCases: ['Remove scanner borders', 'Improve document framing', 'Trim excess whitespace'], faqs: [{ question: 'Does cropping permanently redact content?', answer: 'No. Cropping is not a secure redaction method. Use proper redaction software for sensitive information.' }, { question: 'Can I crop scanned pages?', answer: 'Yes. Cropping is useful for removing scanner edges and excess margins.' }, { question: 'Will the text be changed?', answer: 'The visible page area changes while the remaining content is preserved in the generated copy.' }], related: [{ href: '/tools/rotate', label: 'rotate cropped pages' }, { href: '/tools/page-numbers', label: 'number the PDF pages' }] },
  'HTML to PDF': { keywords: ['HTML to PDF', 'HTML CSS to PDF', 'web page to PDF'], intro: 'Convert HTML and CSS content into a PDF preview for printable documents, simple layouts, and offline sharing.', howTo: ['Enter or paste the HTML content supported by the tool.', 'Preview the rendered document and adjust the markup or styles.', 'Generate and download the PDF when the layout is ready.'], details: 'HTML-to-PDF output depends on browser rendering. External assets, advanced CSS, scripts, and unsupported web fonts may not render exactly as they do on a live website.', useCases: ['Create a printable HTML document', 'Save a simple web layout as PDF', 'Generate a styled offline handout'], faqs: [{ question: 'Can I convert any website URL?', answer: 'The tool works with the HTML content provided in its editor, not as a general website crawler.' }, { question: 'Are scripts executed?', answer: 'The preview is sandboxed, and scripts or browser-only behavior may not be supported.' }, { question: 'Why do external images look different?', answer: 'External resources can be blocked or rendered differently; use supported local content when possible.' }], related: [{ href: '/tools/word-to-pdf', label: 'convert Word documents' }, { href: '/tools/compress', label: 'compress the PDF result' }] },
  'Repair PDF': { keywords: ['repair PDF online', 'fix corrupted PDF', 'recover damaged PDF'], intro: 'Try to recover a readable copy of a damaged or malformed PDF. Keep the original file and compare the repaired output before relying on it.', howTo: ['Select the PDF that fails to open or render correctly.', 'Start the repair process.', 'Download the recovered copy and inspect its pages and content.'], details: 'Repair success depends on what is damaged inside the file. A repair tool cannot guarantee recovery of missing bytes, deleted pages, unsupported encryption, or severely corrupted content.', useCases: ['Attempt recovery of an unreadable PDF', 'Open a file that displays rendering errors', 'Create a fresh copy for archiving'], faqs: [{ question: 'Can every corrupted PDF be repaired?', answer: 'No. Recovery depends on the type and severity of the damage.' }, { question: 'Should I keep the original?', answer: 'Yes. Always preserve the source file and treat the repaired copy as a recovery attempt.' }, { question: 'What if repair fails?', answer: 'Try to obtain another copy, restore a backup, or use a dedicated desktop recovery workflow.' }], related: [{ href: '/tools/compress', label: 'compress a recovered PDF' }, { href: '/tools/merge', label: 'combine recovered pages' }] },
  'Scan PDF': { keywords: ['scan to PDF', 'images to scanned PDF', 'create PDF from scans'], intro: 'Combine scanned images into a clean PDF document for records, forms, receipts, and paper-to-digital workflows.', howTo: ['Select the scanned image files.', 'Arrange pages in reading order and review the preview.', 'Create the PDF and download the scanned document.'], details: 'A good scan starts with sharp, upright images and even lighting. The result is a visual PDF; use OCR when you need selectable or searchable text.', useCases: ['Digitize paper receipts', 'Create a scanned application packet', 'Archive photographed documents'], faqs: [{ question: 'Can I make a searchable scanned PDF?', answer: 'The scan creates a PDF from images. Use the OCR tool afterward when text recognition is needed.' }, { question: 'Can I reorder scan pages?', answer: 'Yes. Arrange the selected images before creating the PDF.' }, { question: 'What image quality is best?', answer: 'Use clear, upright images with enough resolution to read small text.' }], related: [{ href: '/tools/ocr', label: 'OCR the scanned PDF' }, { href: '/tools/images-to-pdf', label: 'create a PDF from images' }] },
};

const profileAliases: Record<string, string> = {
  'Add Page Numbers': 'Page Numbers',
  'Add Watermark': 'Watermark',
  'Add Page Numbers to PDF': 'Page Numbers',
  'OCR PDF': 'OCR Scanner',
  'Scan to PDF': 'Scan PDF',
  'Watermark PDF': 'Watermark',
};

function buildContent(title: string, description: string): ToolSeoContent {
  const profile = profiles[title] ?? profiles[profileAliases[title]];
  if (!profile) {
    throw new Error(`Missing SEO profile for tool: ${title}`);
  }
  const metaTitle = `${profile.keywords[0][0].toUpperCase() + profile.keywords[0].slice(1)} Free | SelfPDF`;
  return { title, description, metaTitle, metaDescription: `${profile.intro} Try SelfPDF in your browser.`, ...profile, privacy: 'SelfPDF is designed for browser-based document processing without an account. Process only files you are authorized to use, and keep a local backup of important originals.' };
}

export function getToolSeoContent(title: string, description: string) { return buildContent(title, description); }

export function ToolSeoContent({ data }: { data: ToolSeoContent }) {
  const faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: data.faqs.map((faq) => ({ '@type': 'Question', name: faq.question, acceptedAnswer: { '@type': 'Answer', text: faq.answer } })) };
  return <section className="mx-auto max-w-4xl space-y-10" aria-label={`${data.title} guide`}>
    <div className="space-y-3"><p className="text-lg leading-7 text-muted-foreground">{data.intro}</p></div>
    <div className="grid gap-8 md:grid-cols-2"><div><h2 className="mb-4 text-2xl font-semibold">How to use {data.title}</h2><ol className="space-y-3 text-muted-foreground">{data.howTo.map((step, i) => <li key={step} className="flex gap-3"><span className="font-semibold text-foreground">{i + 1}.</span><span>{step}</span></li>)}</ol></div><div><h2 className="mb-4 text-2xl font-semibold">About this PDF tool</h2><p className="leading-7 text-muted-foreground">{data.details}</p></div></div>
    <div><h2 className="mb-4 text-2xl font-semibold">Common uses</h2><ul className="grid gap-3 text-muted-foreground sm:grid-cols-3">{data.useCases.map((item) => <li key={item} className="rounded-xl border bg-muted/20 p-4">{item}</li>)}</ul></div>
    <div className="rounded-2xl border bg-muted/20 p-6"><h2 className="mb-3 text-2xl font-semibold">Privacy and local processing</h2><p className="leading-7 text-muted-foreground">{data.privacy}</p></div>
    <div><h2 className="mb-5 text-2xl font-semibold">Frequently Asked Questions</h2><div className="space-y-6">{data.faqs.map((faq) => <div key={faq.question}><h3 className="font-semibold">{faq.question}</h3><p className="mt-2 leading-7 text-muted-foreground">{faq.answer}</p></div>)}</div><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /></div>
    <nav aria-label="Related PDF tools" className="border-t pt-6"><h2 className="mb-3 text-lg font-semibold">Related tools</h2><div className="flex flex-wrap gap-x-5 gap-y-2">{data.related.map((link) => <Link key={link.href} href={link.href} className="text-primary underline-offset-4 hover:underline">{link.label}</Link>)}</div></nav>
  </section>;
}

export function getToolMetadata(title: string, description: string, path: string) { const data = getToolSeoContent(title, description); return { title: data.metaTitle, description: data.metaDescription, keywords: profiles[title]?.keywords, alternates: { canonical: `https://www.selfpdf.xyz${path}` }, openGraph: { title: data.metaTitle, description: data.metaDescription, url: `https://www.selfpdf.xyz${path}`, type: 'website' as const, siteName: 'SelfPDF' }, twitter: { card: 'summary' as const, title: data.metaTitle, description: data.metaDescription } }; }
