import { FileText, Scissors, Minimize2, ImageIcon, FileImage, FileType, RotateCw, Lock, Shield, Droplet, Hash, PenTool, Scan, Type as type, LucideIcon, Presentation, Table, Crop, Code, Wrench, ScanLine, FilePenLine, EyeOff, GitCompare, FileText as TextIcon, Trash2, ListOrdered } from 'lucide-react';

export interface PDFTool {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  href: string;
  category: 'organize' | 'convert' | 'edit' | 'security' | 'intelligence';
  isNew?: boolean;
  color: string;
}

export const pdfTools: PDFTool[] = [
  {
    id: 'merge',
    name: 'Merge PDF',
    description: 'Combine multiple PDFs into one',
    icon: FileText,
    href: '/tools/merge',
    category: 'organize',
    color: 'bg-blue-50 text-blue-600 dark:bg-blue-950 dark:text-blue-400',
  },
  {
    id: 'split',
    name: 'Split PDF',
    description: 'Extract pages from your PDF',
    icon: Scissors,
    href: '/tools/split',
    category: 'organize',
    color: 'bg-purple-50 text-purple-600 dark:bg-purple-950 dark:text-purple-400',
  },
  {
    id: 'compress',
    name: 'Compress PDF',
    description: 'Reduce PDF file size',
    icon: Minimize2,
    href: '/tools/compress',
    category: 'organize',
    color: 'bg-green-50 text-green-600 dark:bg-green-950 dark:text-green-400',
  },
  {
    id: 'pdf-to-images',
    name: 'PDF to Images',
    description: 'Convert PDF pages to PNG/JPG',
    icon: ImageIcon,
    href: '/tools/pdf-to-images',
    category: 'convert',
    color: 'bg-orange-50 text-orange-600 dark:bg-orange-950 dark:text-orange-400',
  },
  {
    id: 'images-to-pdf',
    name: 'Images to PDF',
    description: 'Convert images to PDF',
    icon: FileImage,
    href: '/tools/images-to-pdf',
    category: 'convert',
    color: 'bg-pink-50 text-pink-600 dark:bg-pink-950 dark:text-pink-400',
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert PDF to DOCX format',
    icon: FileType,
    href: '/tools/pdf-to-word',
    category: 'convert',
    color: 'bg-cyan-50 text-cyan-600 dark:bg-cyan-950 dark:text-cyan-400',
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert DOCX to PDF',
    icon: FileType,
    href: '/tools/word-to-pdf',
    category: 'convert',
    color: 'bg-indigo-50 text-indigo-600 dark:bg-indigo-950 dark:text-indigo-400',
  },
  {
    id: 'pdf-editor',
    name: 'PDF Editor',
    description: 'Create and edit PDFs in your browser',
    icon: FilePenLine,
    href: '/pdf-editor',
    category: 'edit',
    color: 'bg-orange-50 text-orange-600 dark:bg-orange-950 dark:text-orange-400',
    isNew: true,
  },
  {
    id: 'rotate',
    name: 'Rotate PDF',
    description: 'Rotate PDF pages',
    icon: RotateCw,
    href: '/tools/rotate',
    category: 'edit',
    color: 'bg-teal-50 text-teal-600 dark:bg-teal-950 dark:text-teal-400',
  },
  {
    id: 'unlock',
    name: 'Unlock PDF',
    description: 'Remove PDF password protection',
    icon: Lock,
    href: '/tools/unlock',
    category: 'security',
    color: 'bg-red-50 text-red-600 dark:bg-red-950 dark:text-red-400',
  },
  {
    id: 'protect',
    name: 'Protect PDF',
    description: 'Add password to your PDF',
    icon: Shield,
    href: '/tools/protect',
    category: 'security',
    color: 'bg-amber-50 text-amber-600 dark:bg-amber-950 dark:text-amber-400',
  },
  {
    id: 'watermark',
    name: 'Watermark',
    description: 'Add watermark to PDF',
    icon: Droplet,
    href: '/tools/watermark',
    category: 'edit',
    color: 'bg-violet-50 text-violet-600 dark:bg-violet-950 dark:text-violet-400',
  },
  {
    id: 'page-numbers',
    name: 'Page Numbers',
    description: 'Add page numbers to PDF',
    icon: Hash,
    href: '/tools/page-numbers',
    category: 'edit',
    color: 'bg-lime-50 text-lime-600 dark:bg-lime-950 dark:text-lime-400',
  },
  {
    id: 'sign',
    name: 'Sign PDF',
    description: 'Digitally sign your PDF',
    icon: PenTool,
    href: '/tools/sign',
    category: 'edit',
    color: 'bg-rose-50 text-rose-600 dark:bg-rose-950 dark:text-rose-400',
  },
  {
    id: 'ocr',
    name: 'OCR Scanner',
    description: 'Extract text from scanned PDFs',
    icon: Scan,
    href: '/tools/ocr',
    category: 'convert',
    color: 'bg-emerald-50 text-emerald-600 dark:bg-emerald-950 dark:text-emerald-400',
  },
  {
    id: 'pdf-to-powerpoint',
    name: 'PDF to PowerPoint',
    description: 'Convert PDF to PPTX format',
    icon: Presentation,
    href: '/tools/pdf-to-powerpoint',
    category: 'convert',
    color: 'bg-red-50 text-red-600 dark:bg-red-950 dark:text-red-400',
  },
  {
    id: 'powerpoint-to-pdf',
    name: 'PowerPoint to PDF',
    description: 'Convert PPTX to PDF',
    icon: Presentation,
    href: '/tools/powerpoint-to-pdf',
    category: 'convert',
    color: 'bg-orange-50 text-orange-600 dark:bg-orange-950 dark:text-orange-400',
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Convert PDF tables to XLSX',
    icon: Table,
    href: '/tools/pdf-to-excel',
    category: 'convert',
    color: 'bg-green-50 text-green-600 dark:bg-green-950 dark:text-green-400',
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Convert XLSX to PDF',
    icon: Table,
    href: '/tools/excel-to-pdf',
    category: 'convert',
    color: 'bg-teal-50 text-teal-600 dark:bg-teal-950 dark:text-teal-400',
  },
  {
    id: 'crop',
    name: 'Crop PDF',
    description: 'Crop and trim PDF page margins',
    icon: Crop,
    href: '/tools/crop',
    category: 'edit',
    color: 'bg-sky-50 text-sky-600 dark:bg-sky-950 dark:text-sky-400',
  },
  {
    id: 'html-to-pdf',
    name: 'HTML to PDF',
    description: 'Convert HTML & CSS to PDF',
    icon: Code,
    href: '/tools/html-to-pdf',
    category: 'convert',
    color: 'bg-fuchsia-50 text-fuchsia-600 dark:bg-fuchsia-950 dark:text-fuchsia-400',
  },
  {
    id: 'repair',
    name: 'Repair PDF',
    description: 'Fix and repair corrupted PDFs',
    icon: Wrench,
    href: '/tools/repair',
    category: 'organize',
    color: 'bg-yellow-50 text-yellow-600 dark:bg-yellow-950 dark:text-yellow-400',
  },
  {
    id: 'pdf-to-markdown',
    name: 'PDF to Markdown',
    description: 'Convert PDF text into editable Markdown',
    icon: Code,
    href: '/tools/pdf-to-markdown',
    category: 'intelligence',
    color: 'bg-violet-50 text-violet-600 dark:bg-violet-950 dark:text-violet-400',
    isNew: true,
  },
  {
    id: 'fill-pdf', name: 'Fill PDF', description: 'Fill PDF forms in your browser', icon: FilePenLine, href: '/tools/fill-pdf', category: 'edit', color: 'bg-blue-50 text-blue-600 dark:bg-blue-950 dark:text-blue-400', isNew: true,
  },
  {
    id: 'redact-pdf', name: 'Redact PDF', description: 'Hide sensitive content in PDFs', icon: EyeOff, href: '/tools/redact-pdf', category: 'security', color: 'bg-red-50 text-red-600 dark:bg-red-950 dark:text-red-400', isNew: true,
  },
  {
    id: 'compare-pdf', name: 'Compare PDF', description: 'Compare two PDF documents', icon: GitCompare, href: '/tools/compare-pdf', category: 'organize', color: 'bg-indigo-50 text-indigo-600 dark:bg-indigo-950 dark:text-indigo-400', isNew: true,
  },
  {
    id: 'pdf-to-jpg', name: 'PDF to JPG', description: 'Convert PDF pages to JPG', icon: ImageIcon, href: '/tools/pdf-to-jpg', category: 'convert', color: 'bg-orange-50 text-orange-600 dark:bg-orange-950 dark:text-orange-400', isNew: true,
  },
  {
    id: 'pdf-to-png', name: 'PDF to PNG', description: 'Convert PDF pages to PNG', icon: ImageIcon, href: '/tools/pdf-to-png', category: 'convert', color: 'bg-pink-50 text-pink-600 dark:bg-pink-950 dark:text-pink-400', isNew: true,
  },
  {
    id: 'pdf-to-text', name: 'PDF to Text', description: 'Extract text from PDF files', icon: TextIcon, href: '/tools/pdf-to-text', category: 'convert', color: 'bg-cyan-50 text-cyan-600 dark:bg-cyan-950 dark:text-cyan-400', isNew: true,
  },
  {
    id: 'delete-pdf-pages', name: 'Delete PDF Pages', description: 'Remove pages from a PDF', icon: Trash2, href: '/tools/delete-pdf-pages', category: 'organize', color: 'bg-rose-50 text-rose-600 dark:bg-rose-950 dark:text-rose-400', isNew: true,
  },
  {
    id: 'reorder-pdf-pages', name: 'Reorder PDF Pages', description: 'Rearrange PDF pages', icon: ListOrdered, href: '/tools/reorder-pdf-pages', category: 'organize', color: 'bg-teal-50 text-teal-600 dark:bg-teal-950 dark:text-teal-400', isNew: true,
  },
  {
    id: 'scan',
    name: 'Scan PDF',
    description: 'Scan images into a PDF document',
    icon: ScanLine,
    href: '/tools/scan',
    category: 'convert',
    color: 'bg-stone-50 text-stone-600 dark:bg-stone-950 dark:text-stone-400',
  },
];

export const toolCategories = [
  { id: 'organize', name: 'Organize', description: 'Merge, split, and organize PDFs' },
  { id: 'convert', name: 'Convert', description: 'Convert PDFs to other formats' },
  { id: 'edit', name: 'Edit', description: 'Edit and modify your PDFs' },
  { id: 'security', name: 'Security', description: 'Protect and secure your PDFs' },
  { id: 'intelligence', name: 'PDF Intelligence', description: 'Extract and prepare PDF content for AI workflows' },
] as const;
